version: "3"

services:
  mysql:
    # 필요한가?
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul # North Virginia 같은 외국 서버를 쓸 땐 이렇게 줘야함
    volumes:
      - mysql:/var/lib/mysql
      - ./config/mysql/:/etc/mysql/conf.d
    ports:
      - "3306:3306"

# volume이 필요할까.
volumes:
  mysql:
